// Mocks generated by Mockito 5.4.4 from annotations
// in yandeh_challenge/test/features/home/domain/usecases/get_sections_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:yandeh_challenge/features/home/domain/entities/section.dart'
    as _i4;
import 'package:yandeh_challenge/features/home/domain/repositories/i_sections_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ISectionsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockISectionsRepository extends _i1.Mock
    implements _i2.ISectionsRepository {
  MockISectionsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Section>> getSections({
    bool? originalSections,
    String? argument,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSections,
          [],
          {
            #originalSections: originalSections,
            #argument: argument,
          },
        ),
        returnValue: _i3.Future<List<_i4.Section>>.value(<_i4.Section>[]),
      ) as _i3.Future<List<_i4.Section>>);
}
